version: '1'
services:
  one-hour-one-life:
    build:
      context: .
    image: hunter13wright/one-hour-one-life:v1
    hostname: one-hour-one-life
    container_name: 'one-hour-one-life'
    ports:
      - '8005:8005'

    volumes:
      - '.:/opt/src'

    networks:
      - app

networks:
  default:
    driver: bridge
  app:
    driver: bridge
